networks:
  local_network:
    driver: bridge
    external: true

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: ${APP_NAME}
    ports:
      - "${APP_PORT}:8080"
      - "50000:50000"
    networks:
      - local_network
    volumes:
      - /home/${USER}/.ssh:/var/jenkins_home/.ssh:ro
      - ${CONTAINERS_APP_DIR}/data:/var/jenkins_home
      - ${CONTAINERS_APP_DIR}/conf:/usr/local/etc
    environment:
      - JAVA_OPTS=-Duser.timezone=Asia/Shanghai
    restart: on-failure