networks:
  local_network:
    driver: bridge
    external: true

services:
  kafka-ui:
    image: ghcr.io/kafbat/kafka-ui
    container_name: ${APP_NAME}
    ports:
      - "${APP_PORT}:8080"
    networks:
      - local_network
    environment:
      - KAFKA_CLUSTERS_0_NAME=${KAFKA_CLUSTERS_0_NAME}
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=${KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS}
      - AUTH_TYPE=${AUTH_TYPE}
      - SPRING_SECURITY_USER_NAME=${SPRING_SECURITY_USER_NAME}
      - SPRING_SECURITY_USER_PASSWORD=${SPRING_SECURITY_USER_PASSWORD}