networks:
  local_network:
    external: true

services:
  rustfs:
    image: rustfs/rustfs:latest
    container_name: ${APP_NAME}
    ports:
      - "${APP_PORT}:9000"
      - "${CONSOLE_PORT}:9001"
    networks:
      - local_network
    volumes:
      - ${CONTAINERS_APP_DIR}/data:/data
      - ${CONTAINERS_APP_DIR}/logs:/logs
    environment:
      - RUSTFS_ACCESS_KEY=${ROOT_USER}
      - RUSTFS_SECRET_KEY=${ROOT_PASSWORD}
      - RUSTFS_CONSOLE_ENABLE=true