networks:
  local_network:
    driver: bridge
    external: true

services:
  redis:
    image: redis:latest
    container_name: ${APP_NAME}
    ports:
      - "${APP_PORT}:6379"
    networks:
      - local_network
    volumes:
      - ${CONTAINERS_APP_DIR}/data:/data
      - ${CONTAINERS_APP_DIR}/conf:/usr/local/etc
    entrypoint: ["redis-server","/usr/local/etc/redis.conf"]