networks:
  local_network:
    driver: bridge
    external: true

services:
  redis:
    image: redis:latest
    container_name: ${APP_NAME}
    ports:
      - "${APP_PORT}:6379"
    networks:
      - local_network
    environment:
      - KAFKA_CLUSTERS_0_NAME=${KAFKA_CLUSTERS_0_NAME}
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=${KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS}
      - AUTH_TYPE=${AUTH_TYPE}
      - SPRING_SECURITY_USER_NAME=${SPRING_SECURITY_USER_NAME}
      - SPRING_SECURITY_USER_PASSWORD=${SPRING_SECURITY_USER_PASSWORD}
    volumes:
      - ${CONTAINERS_APP_DIR}/data:/data
      - ${CONTAINERS_APP_DIR}/conf:/usr/local/etc
    entrypoint: ["redis-server","/usr/local/etc/redis.conf"]