listen: :8443
trafficStats:
  listen: :8445

tls:
  cert: /etc/server.crt
  key: /etc/server.key
auth:
  type: password
  password: 123456
  http:
    url: http://11123.com
ignoreClientBandwidth: false
masquerade:
  type: proxy
  proxy:
    url: https://www.bing.com
    rewriteHost: true